package visao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import persistence.Pacientes;


public class TelaExames extends javax.swing.JFrame {

    public static String cpf;
    private String cargo;
    private String nome;

    public TelaExames() {
        initComponents();
    }

    public TelaExames(String nome, String cargo) {
        initComponents();
        this.cargo = cargo;
        this.nome = nome;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        btnConsulta = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        TelaExames = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFerramentas = new javax.swing.JMenu();
        itmConsultar = new javax.swing.JMenuItem();
        itmVoltar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaExames");
        getContentPane().setLayout(null);

        lblCpf.setText("CPF");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(200, 130, 30, 30);

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(230, 130, 170, 30);

        btnConsulta.setText("Consultar");
        btnConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultaMouseClicked(evt);
            }
        });
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsulta);
        btnConsulta.setBounds(260, 170, 90, 23);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(80, 0, 180, 120);

        TelaExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/background Projeto_1.jpg"))); // NOI18N
        getContentPane().add(TelaExames);
        TelaExames.setBounds(0, -20, 440, 240);

        mnuFerramentas.setText("Ferramentas");

        itmConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/consultar_zinho.png"))); // NOI18N
        itmConsultar.setText("Consultar");
        itmConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultarActionPerformed(evt);
            }
        });
        mnuFerramentas.add(itmConsultar);

        itmVoltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/voltar.png"))); // NOI18N
        itmVoltar.setText("Voltar");
        itmVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmVoltarActionPerformed(evt);
            }
        });
        mnuFerramentas.add(itmVoltar);
        mnuFerramentas.add(jSeparator1);

        itmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        itmSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sair.png"))); // NOI18N
        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        mnuFerramentas.add(itmSair);

        jMenuBar1.add(mnuFerramentas);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(455, 277));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        dispose();
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmVoltarActionPerformed

        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_itmVoltarActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed


        try {
            // Conectar com o BD
            Connection con;
            PreparedStatement st;
            ResultSet rs;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoacesso", "root", "tico0715612!");
            st = con.prepareStatement("SELECT * FROM paciente WHERE cpf = ?");
            st.setString(1, txtCpf.getText());
            rs = st.executeQuery();

            if (rs.next()) { // Se encontrou o usuario no BD
                Pacientes model = new Pacientes();
                model.setCpf(txtCpf.getText());
                TelaConsulta t;
                t = new TelaConsulta(rs.getString("cpf"),this.cargo,this.nome);
                t.exportarCpf(model);
                t.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha não encontrados");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de acesso ao Banco de dados. \n Entre em contato com o administrador do sistema e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void itmConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsultarActionPerformed

        try {
            // Conectar com o BD
            Connection con;
            PreparedStatement st;
            ResultSet rs;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoacesso", "root", "tico0715612!");
            st = con.prepareStatement("SELECT * FROM paciente WHERE cpf = ?");
            st.setString(1, txtCpf.getText());
            rs = st.executeQuery();

            if (rs.next()) { // Se encontrou o usuario no BD
                Pacientes model = new Pacientes();
                model.setCpf(txtCpf.getText());
                TelaConsulta t;
                t = new TelaConsulta(rs.getString("cpf"),this.cargo,this.nome);
                t.exportarCpf(model);
                t.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha não encontrados");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de acesso ao Banco de dados. \n Entre em contato com o administrador do sistema e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmConsultarActionPerformed

    private void btnConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaMouseClicked

    }//GEN-LAST:event_btnConsultaMouseClicked

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaExames;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JMenuItem itmConsultar;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuItem itmVoltar;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JMenu mnuFerramentas;
    private javax.swing.JTextField txtCpf;
    // End of variables declaration//GEN-END:variables
}
