package visao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import persistence.Pacientes;

public class TelaConsulta extends javax.swing.JFrame {

    public static String cpf;
    public String nome;


    public TelaConsulta(String nome) {
        initComponents();
        this.nome = nome;

        
    }



    /**
     * Creates new form TelaConsulta
     */
    public TelaConsulta() {
        initComponents();
        
    }

    public TelaConsulta(String cpf, String cargo, String nome) {
        initComponents();
        lblAssinadoNome.setText("Assinado Por " + nome);    
        // Sumir com os botões
        btnNovaColsulta.setVisible(false);
        btnImprimir.setVisible(false);
        btnAssinar.setVisible(false);
        lblAssinadoNome.setVisible(false);
        
        if (cargo.equalsIgnoreCase("Medico")) {
            
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
        } else if (cargo.equalsIgnoreCase("Recepcionista")) {
            
            btnAssinar.setEnabled(false);
            btnImprimir.setEnabled(false);
        }
    }

    public void exportarCpf(Pacientes model) {

        txtCpf.setText(model.getCpf());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        txtStatusExame = new javax.swing.JTextField();
        lblStatusExame = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnVerConsulta = new javax.swing.JButton();
        btnNovaColsulta = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAssinar = new javax.swing.JButton();
        txtCpf = new javax.swing.JTextField();
        txtConvenio = new javax.swing.JTextField();
        lblConvenio = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblAssinadoNome = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblTela = new javax.swing.JLabel();

        setTitle("TelaConsulta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        txtNome.setEditable(false);
        getContentPane().add(txtNome);
        txtNome.setBounds(310, 110, 210, 30);

        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(270, 110, 40, 30);

        txtDataNascimento.setEditable(false);
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataNascimento);
        txtDataNascimento.setBounds(310, 190, 100, 30);

        lblDataNascimento.setText("Data de  Nascimento");
        getContentPane().add(lblDataNascimento);
        lblDataNascimento.setBounds(190, 190, 120, 30);

        txtStatusExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusExameActionPerformed(evt);
            }
        });
        getContentPane().add(txtStatusExame);
        txtStatusExame.setBounds(310, 230, 100, 30);

        lblStatusExame.setText("Status Exame");
        getContentPane().add(lblStatusExame);
        lblStatusExame.setBounds(230, 230, 80, 30);

        txtTelefone.setEditable(false);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(310, 270, 150, 30);

        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(250, 270, 60, 30);

        txtEndereco.setEditable(false);
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(310, 310, 210, 30);

        lblEndereco.setText("Endereço");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(250, 310, 60, 30);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(100, 350, 80, 30);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir);
        btnImprimir.setBounds(190, 350, 90, 30);

        btnVerConsulta.setText("Ver consulta");
        btnVerConsulta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnVerConsultaItemStateChanged(evt);
            }
        });
        btnVerConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerConsultaMouseClicked(evt);
            }
        });
        btnVerConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerConsulta);
        btnVerConsulta.setBounds(420, 350, 110, 30);

        btnNovaColsulta.setText("Nova Colsulta");
        btnNovaColsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaColsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovaColsulta);
        btnNovaColsulta.setBounds(420, 350, 110, 30);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(10, 350, 80, 30);

        btnAssinar.setText("Assinar");
        btnAssinar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnAssinarItemStateChanged(evt);
            }
        });
        btnAssinar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAssinarMouseClicked(evt);
            }
        });
        btnAssinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssinarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAssinar);
        btnAssinar.setBounds(320, 350, 90, 30);

        txtCpf.setEditable(false);
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(310, 70, 210, 30);

        txtConvenio.setEditable(false);
        getContentPane().add(txtConvenio);
        txtConvenio.setBounds(310, 150, 210, 30);

        lblConvenio.setText("Convenio");
        getContentPane().add(lblConvenio);
        lblConvenio.setBounds(250, 150, 60, 30);

        lblCpf.setText("Cpf");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(270, 70, 40, 30);
        getContentPane().add(lblAssinadoNome);
        lblAssinadoNome.setBounds(240, 20, 300, 30);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Logo.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(90, 40, 180, 120);

        lblTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/background Projeto_1.jpg"))); // NOI18N
        getContentPane().add(lblTela);
        lblTela.setBounds(0, 0, 550, 400);

        setSize(new java.awt.Dimension(565, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStatusExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusExameActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        try {
            //Conectar no Banco de Dados
            Connection con;
            PreparedStatement st;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoacesso", "root", "tico0715612!");
            st = con.prepareStatement("DELETE FROM paciente WHERE cpf = ?");
            st.setString(1, txtCpf.getText());

            // EXECUTAR O DELETE NO BANCO DE DADOS
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cliente excluido com sucesso");

            //Limpar campos
            limpar();

            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);

            //Caso der erro no DRIVE 
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no acesso à base de dados. Entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        try {
            // Conectar com o BD
            Connection con;
            PreparedStatement st;
            ResultSet rs;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoacesso", "root", "tico0715612!");
            st = con.prepareStatement("SELECT * FROM paciente WHERE cpf = ?");
            st.setString(1, txtCpf.getText());
            rs = st.executeQuery();

            if (rs.next()) { // Se encontrou o usuario no BD
                Pacientes model = new Pacientes();
                model.setCpf(txtCpf.getText());
                TelaImprimir tel;
                tel = new TelaImprimir();
                tel.exportarCpf(model);
                tel.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha não encontrados");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de acesso ao Banco de dados. \n Entre em contato com o administrador do sistema e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnAssinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssinarActionPerformed

            txtStatusExame.setEnabled(false);
            btnImprimir.setVisible(true);
            lblAssinadoNome.setVisible(true);


    }//GEN-LAST:event_btnAssinarActionPerformed

    private void btnNovaColsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaColsultaActionPerformed

        TelaExames tela = new TelaExames();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnNovaColsultaActionPerformed

    private void limpar() {
        txtCpf.setText("");
        txtNome.setText("");
        txtConvenio.setText("");
        txtDataNascimento.setText("");
        txtStatusExame.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtCpf.requestFocus();
    }

    private void btnVerConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerConsultaActionPerformed

        try {
            // Conectar no BD
            Connection con;
            PreparedStatement st;
            ResultSet rs;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoacesso", "root", "tico0715612!");
            // Fazer a busca do CPF digitado no Campo
            st = con.prepareStatement("SELECT * FROM paciente WHERE cpf = ?");
            st.setString(1, txtCpf.getText());
            rs = st.executeQuery(); // EXECUTA O SELECT NA TABELA DO BD
            
            if (rs.next()) { // Se encontrou o CPF no BD
                txtCpf.setText(rs.getString("cpf"));
                txtNome.setText(rs.getString("nome"));
                txtConvenio.setText(rs.getString("convenio"));
                txtDataNascimento.setText(rs.getString("datanascimento"));
                txtStatusExame.setText(rs.getString("statusexame"));
                txtTelefone.setText(rs.getString("telefone"));
                txtEndereco.setText(rs.getString("endereco"));
                btnVerConsulta.setVisible(false);
                btnNovaColsulta.setVisible(true);
                if (!"Pronto".equals(txtStatusExame.getText())){
                }else{
                    btnAssinar.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no acesso à base de dados. Entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnVerConsultaActionPerformed

    private void btnVerConsultaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnVerConsultaItemStateChanged

    }//GEN-LAST:event_btnVerConsultaItemStateChanged

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed


    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        try {
            // conectar ao BD
            Connection con;
            PreparedStatement st;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoacesso", "root", "tico0715612!");

            // Executar a alteração (Update)
            st = con.prepareStatement("UPDATE paciente SET nome=?, convenio=?, datanascimento=?, statusexame=?, telefone=?, endereco=? WHERE cpf=?");
            st.setString(1, txtNome.getText());
            st.setString(2, txtConvenio.getText());
            st.setString(3, txtDataNascimento.getText());
            st.setString(4, txtStatusExame.getText());
            st.setString(5, txtTelefone.getText());
            st.setString(6, txtEndereco.getText());
            st.setString(7, txtCpf.getText());
            st.executeUpdate();

            // Dar um feedback para o usuário
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");
            limpar();
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            txtStatusExame.setEnabled(false);
            txtCpf.setEditable(true);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na alteração dos dados " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnAssinarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnAssinarItemStateChanged

    }//GEN-LAST:event_btnAssinarItemStateChanged

    private void btnAssinarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssinarMouseClicked


    }//GEN-LAST:event_btnAssinarMouseClicked

    private void btnVerConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerConsultaMouseClicked


    }//GEN-LAST:event_btnVerConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAssinar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNovaColsulta;
    private javax.swing.JButton btnVerConsulta;
    private javax.swing.JLabel lblAssinadoNome;
    private javax.swing.JLabel lblConvenio;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblStatusExame;
    private javax.swing.JLabel lblTela;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtConvenio;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtStatusExame;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

}
